### ISSUE TITLE
Dashboard for purchase order

### ISSUE THREAD

**Issue by Samyukta-b** [acmpesuecc/vendor-system#2]
Create an endpoint that displays a neatly formatted dashboard providing a high-level overview of all the purchase order details present in the database.

**Comment by himaniraoo** [comment]
can you please assign this to me @Samyukta-b

**Comment by ShadowMarty** [comment]
please assign me this issue

**Comment by Samyukta-b** [comment]
!assign @himaniraoo

**Comment by Samyukta-b** [comment]
the bot will automatically deassign you in 30 mins. if you show progress and need time, i can extend the timings for you. i will be able to see your progress through the commits in your fork.

**Comment by himaniraoo** [comment]
hey @Samyukta-b , can i please get some more time , installations is taking time ! , i've done some progressing in forking the repository , the wifi is slow so things haven't installed yet

**Comment by Samyukta-b** [comment]
!assign @himaniraoo 60

**Comment by Samyukta-b** [comment]
!extend 60

**Comment by himaniraoo** [comment]
@Samyukta-b , we've been asked to have dinner , please extend time :')

**Comment by Samyukta-b** [comment]
show progress if you want me to extend otherwise i will have to assign it to someone else.

**Comment by Samyukta-b** [comment]
!deassign

**Comment by Samyukta-b** [comment]
@himaniraoo let me know when you're back from dinner and i'll reassign you but you need to show progress

**Comment by MeghanaK11** [comment]
Can you assign me to this

**Comment by Samyukta-b** [comment]
!assign @ShadowMarty 30

**Comment by Samyukta-b** [comment]
!assign @ShadowMarty 30

**Comment by Git-Cat-21** [comment]
can i be assigned to it

**Comment by Samyukta-b** [comment]
!assign @Git-Cat-21 60

**Comment by Git-Cat-21** [comment]
im unable to work on it please deassign

**Comment by Samyukta-b** [comment]
!deassign

**Comment by Samyukta-b** [comment]
@himaniraoo would you like to be assigned to this?

**Comment by diyah1234** [comment]
can I be assigned to this?

**Comment by Samyukta-b** [comment]
!assign @diyah1234 60

**Comment by Samyukta-b** [comment]
@diyah1234 hi, how's it going? i'd like to see some sort of progress in the form of commits please!

**Comment by diyah1234** [comment]
hi, I had to make the required installations, just finished, will commit changes in a while. please give me some time?

**Comment by Samyukta-b** [comment]
okay cool, if you need me to extend time, let me know! @diyah1234

**Comment by diyah1234** [comment]
hi, I am just final testing it, can you extend the time?

**Comment by Samyukta-b** [comment]
!extend 30

**Comment by Samyukta-b** [comment]
!deassign

**Comment by Samyukta-b** [comment]
!assign @diyah1234 30

**Comment by diyah1234** [comment]
hi, I am sending the pull request now

**Comment by Samyukta-b** [comment]
okay

**Comment by Samyukta-b** [comment]
!deassign

**Comment by Samyukta-b** [comment]
!assign @diyah1234 20

**Comment by Samyukta-b** [comment]
!deassign

**Comment by Samyukta-b** [comment]
!assign @diyah1234 30

**Comment by Git-Cat-21** [comment]
please de assign

**Comment by Anyaaa-2** [comment]
can you please assign this to me

**Comment by Samyukta-b** [comment]
this was resolved by #6

**Comment by Samyukta-b** [comment]
!assign @diyah1234 45

**Comment by Samyukta-b** [comment]
!deassign

**Comment by Samyukta-b** [comment]
!assign @diyah1234 45

**Comment by Samyukta-b** [comment]
this issue has been resolved #6

**Comment by Samyukta-b** [comment]
!deassign
