### ISSUE TITLE
Incomplete status update test

### ISSUE THREAD

**Issue by Samyukta-b** [acmpesuecc/vendor-system#4]
In `test_models.py` there is an incomplete status update test. In the `test_order_status_update` method, the test does not actually update the order's status. After creating the order, you need to change its status to 'completed' before calling `refresh_from_db()`. Currently, the test only creates the order and then checks its status without making any updates, which defeats the purpose of the test. Fix this.

**Comment by JSohamRao** [comment]
Can i be assigned this

**Comment by Samyukta-b** [comment]
!assign @JSohamRao

**Comment by Samyukta-b** [comment]
the bot will automatically deassign you in 30 mins. if you show progress and need time, i can extend the timings for you. i will be able to see your progress through the commits in your fork.

**Comment by Samyukta-b** [comment]
!deassign

**Comment by Viprakshi** [comment]
can you please assign me this issue?

**Comment by Viprakshi** [comment]
@Samyukta-b

**Comment by Samyukta-b** [comment]
!assign @Viprakshi 60

**Comment by Samyukta-b** [comment]
I've gone for dinner give me some time, I'll come back and assign

**Comment by Viprakshi** [comment]
tried fixing this issue and pulled a request

**Comment by RisuKumari11** [comment]
can i get assigned this

**Comment by Samyukta-b** [comment]
this issue was resolved by #5

**Comment by Samyukta-b** [comment]
!deassign
